# Generated by Django 6.1.1 on 2026-09-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='situation',
            field=models.BooleanField(default=True),
        ),
    ]
