# Generated by Django 6.1.1 on 2026-09-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
