# Generated by Django 6.1.1 on 2026-09-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_course_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
